### ISSUE TITLE
Add examples in the wild

### ISSUE THREAD

**Issue by colinbendell** [ChartsCSS/ChartsCSS.org#6]
If you are interested in adding a section of example sites using chartscss in the wild, you could add: https://covid19.colinbendell.dev/

**Comment by ramiy** [comment]
@colinbendell This is really amazing!!!

Love the trendline when hovering over the chart. And the way you control colors!

Can I use your technique in the documentation?

```
table.column td {
  --color-1: rgba(253, 126, 20, 0.2);
}
table.column td:nth-child(n+8):not(:last-child) {
  --color-1: rgba(253, 126, 20, 0.6);
}
table.column td:last-child {
  --color-1: repeating-linear-gradient(
    135deg, var(--orange), var(--orange) 3px, var(--light) 3px, var(--light) 5px
  );
}
```

I was impressed, the use of `:nth-child()` and `:last-child` pseudo-classes in this case is genius.

**Comment by colinbendell** [comment]
for sure! Take whatever makes sense. I wasn't sure if trendline feature would make sense, if it does, I'm happy to contribute a PR for that. (probably needs better naming than the use of `--size`)

The use case in the block you copied was specifically to indicate when the data was delayed (eg: reporting yesterday's value vs. today's value). 

One thing I've been experimenting with this dashboard is the notion of data progressive enhancements. That is, trying to let the human not feel overwhelmed with too much data (though there is a lot) and provide more insights and nuances when you hover.

The other thing for me was to make this an exercise of no javascript and 3p no dependencies. The performance is generally pretty good this way, though it does have some 2600 dom nodes because of the complex tables :)

**Comment by ramiy** [comment]
@colinbendell I've added a new section "[Use Pseudo Classes](https://chartscss.org/components/colors/#use-pseudo-classes)" to the **Colors** component.
